### ISSUE TITLE
Create one or more issues for each TODO in source code

### ISSUE THREAD

**Issue by cemsbr** [kytos/python-openflow#82]
TODOs are easy to be forgotten, so here they are (v0x01):

- [x] asynchronous/error_msg.py: Implement the unpack method evaluation the error_type and code
- [x] common/queue.py: Set porp_header attributes
- [x] foundation/basic_types.py: Refactor unpack methods to return the unpacked object
- [x] foundation/basic_types.py: Raise the proper exception here
- [x] foundation/basic_types.py: raise the proper exception here
- [x] foundation/basic_types.py: check for attribute types and overflow behaviour
- [x] foundation/basic_types.py: Raise a proper lib exception

**Comment by beraldoleal** [comment]
Let's migrate each TODO to github creating one issue for each one, with a good description. (Maybe few TODOs can be merged into one issue, like "raise exceptions TODOs".

**Comment by diraol** [comment]
common/queue TODO fixed at: b369913

**Comment by cemsbr** [comment]
The last 4 will are in issue #100.

**Comment by beraldoleal** [comment]
Lets create one issue per TODO. @cemsbr please review this.

**Comment by cemsbr** [comment]
Created #130.
